name: .NET Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ClassToXaml.Skia.WPF/ClassToXaml.Skia.WPF.csproj

    - name: Build
      run: dotnet build ClassToXaml.Skia.WPF/ClassToXaml.Skia.WPF.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test ClassToXaml.Skia.WPF/ClassToXaml.Skia.WPF.csproj --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish ClassToXaml.Skia.WPF/ClassToXaml.Skia.WPF.csproj --configuration Release --no-build --output ./published
